---
title: "R Users"
---

Welcome R people 👋

## What you'll find here  

Welcome! This guide walks you step by step through working with LIS data in R — from getting started to building a solid, reproducible workflow.  

You’ll learn how to navigate the structure and specific features of LIS datasets, while developing practical skills you can apply directly to your own projects. We cover each stage of the workflow, highlight common operations, and share tips to help you work more efficiently.  

Most examples rely on the in-house R package `lissyrtools`, designed to simplify and streamline your interaction with LIS data.  

Whether you're new to LIS or looking to improve your workflow, this guide aims to provide a clear and hands-on learning experience.  

If you have any questions or feedback, feel free to contact the LIS team.

## Additional Resources  

- The R package [`lissyrtools`](https://lis-cross-national-data-center.github.io/lissyrtools/index.html)  
- [Self-Teaching Resources](https://www.lisdatacenter.org/resources/self-teaching/)